version: '3.7'

services:

  web:
    container_name: 'koshelektesttask'
    image: 'koshelektesttask'
    build:
      context: .
      dockerfile: aspnetcore.dockerfile
    ports:
     - "5000:5000"
    depends_on:
     - "postgres"
    networks:
      - koshelektesttask-network

  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_USER: asp
      POSTGRES_PASSWORD: asppassword
      POSTGRES_DB: aspdb
    networks:
      - koshelektesttask-network

networks:
  koshelektesttask-network:
    driver: bridge
